<?php

namespace database\factories;

use Faker\Generator as Faker;

class ExpenseFactory
{
    public static function getFactory(Faker $faker)
    {
        return [
            'equipment_source' => 'NA',
            'pestcide_type_used' => [],
            'planting_service_provider' => 'NA',
            'fertilizer_cost' => [],
            'time' => '2019-03-19T09:31:43.025Z',
            'enterprise_insured' => 'NA',
            'soil_testing_costs' => 'NA',
            'was_loan_accessed' => 'NA',
            'land_mapped_cost' => 'NA',
            'planting_method_used' => 'NA',
            'spraying_cost' => 'NA',
            'crop_insurance_obstacles' => 'NA',
            'acreage_insured' => 'NA',
            'fertilizers_type_used' => [],
            'storage_cost' => 'NA',
            'land_ownership_status' => 'NA',
            'farmer_id' => 'AFAHAJOH788007645RUKNYA',
            'do_you_own_land' => 'NA',
            'threshing_method' => 'NA',
            'soil_test_service_provider' => 'NA',
            'pestcide_variety_used' => [],
            'pulping_cost' => 'NA',
            'shelling_cost' => 'NA',
            'pestcide_cost' => [],
            'equipment_cost' => 'NA',
            'land_cost_rent_or_leased' => 'NA',
            'land_clearing_cost' => 'NA',
            'peril_insured' => 'NA',
            'post_harvest_transport_method' => 'NA',
            'pulping_type' => 'NA',
            'storage_provider' => 'NA',
            'plant_spacing' => 'NA',
            '_id' => $faker->uuid,
            'equipment_type' => 'NA',
            'chemical_variety_used' => [],
            'crop_insurance_service_provider' => 'NA',
            'vaId' => 'AK/MA/0421/0001',
            'seed_source' => 'NA',
            'loan_service_provider' => 'NA',
            'drying_cost' => 'NA',
            'post_harvest_transport_cost' => 'NA',
            'chemicals_cost' => [],
            'threshing_cost' => 'NA',
            'post_harvest_transport_service_provider' => 'NA',
            'loan_amount' => 'NA',
            'value_chain_variety' => ['Bazooka', 'Nabe 14'],
            'crop_insurance_costs' => 'NA',
            'weeding_method' => 'NA',
            'pulping_service_provider' => 'NA',
            'spraying_method' => 'NA',
            'chemicals_quantity' => [],
            'chemical_type_used' => [],
            'shelling_service_provider' => 'NA',
            'value_chain' => ['Maize', 'Beans'],
            'interest' => 10,
            'threshing_service_provider' => 'NA',
            'ploughing_equipment' => 'NA',
            'planting_cost' => 'NA',
            'planting_date' => 'NA',
            'type' => 'expenses',
            'eloquent_type' => 'expenses',
            'drying_method' => 'NA',
            'weeding_cost' => 'NA',
            'harvest_costs' => 'NA',
            'pro_fertilizer_source' => 'NA',
            'fertiliser_quantity' => [],
            'was_crop_insurance_accessed' => 'NA',
            'harvest_methods' => 'NA',
            'was_the_soil_tested' => 'NA',
            'partner_id' => 'NA',
            'seed_costs' => [30000, 50000],
            'shelling_method' => 'NA',
            'spraying_service_provider' => 'NA',
            'ma_id' => 'AK/MA/0421',
            'land_ploughing_cost' => 'NA',
            'seed_quantity' => [2, 5],
            'storage_type' => 'NA',
            'drying_service_provider' => 'NA',
            'weeding_service_providers' => 'NA',
            'harvest_service_provider' => 'NA',
            'chemicals_source' => 'NA',
            'pestcide_quantity' => []
        ];
    }
}
